name: Build-The-Package
on:
  push:
    branches:
      - main
jobs:
  widget-build-action:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn
        ##   Here is this Action
      - uses: ahwelgemoed/mendix-widget-build-action@main
        with:
          author_name: build-bot
          branch_to_push_to: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          bot_commit_message: bot-version-match
          bot_author_name: build-bot
          bot_author_email: build-bot@mendix.com
